version: 0.2

env:
  secrets-manager:
    # You can set the next values hardcoded or to use the agent outputs like here: https://github.com/Senora-dev/self-service-backend
    PORT_CLIENT_SECRET: 'PUT_SECRET_ARN_HERE'
    PORT_CLIENT_ID: 'PUT_SECRET_ARN_HERE'
    
phases:
  install:
    commands:
      - sudo yum -y install jq
  
  pre_build:
    commands:
      # Generate access token for Run status update using Port API.
      - >-
        ACCESS_TOKEN=$(curl --location --request POST 'https://api.getport.io/v1/auth/access_token' --header 'Content-Type: application/json' --data-raw '{"clientId": "'"$PORT_CLIENT_ID"'","clientSecret": "'"$PORT_CLIENT_SECRET"'"}' | jq '.accessToken' | sed 's/"//g')

      # Get run_id from Payload.
      - cd $CODEBUILD_SRC_DIR_runs_bucket
      - RUN_ID=$(cat payload.json| jq -r '.context.runId')
      - echo $RUN_ID
      
  build:
    commands:
      # Execute any command you want as a self-service operation.
       - echo "Your self-service operation is running here."
       
  post_build:
    commands:
      # Update Run status in Port - Don't forget (!) to set the status and comment by the operation result.
       - echo "Updating status in Port:"
       - >- 
        curl -X PATCH https://api.getport.io/v1/actions/runs/$RUN_ID -H 'Content-Type: application/json' -H 'Accept: application/json' -H "Authorization: Bearer $ACCESS_TOKEN"  -d '{"status": "SUCCESS", "message": {"run_status": "Run completed successfully!"}}'
